
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `t_employee`;
CREATE TABLE `t_employee` (
	`id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '用户id',
	`group_id` VARCHAR(20) NULL DEFAULT NULL COMMENT '分组id',
	`user_id` VARCHAR(50) NULL DEFAULT NULL,
	`create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
	`create_by` BIGINT(50) NULL DEFAULT NULL COMMENT '创建人',
	`update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
	`update_by` BIGINT(50) NULL DEFAULT NULL COMMENT '更新人',
	PRIMARY KEY (`id`)
)
COMMENT='员工表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=41
;
DROP TABLE IF EXISTS `t_veinfeat`;
CREATE TABLE `t_veinfeat` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '静脉id',
	`user_id` VARCHAR(50) NOT NULL,
	`vein_feat` CHAR(64) NOT NULL COMMENT '用户静脉',
	`create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
	`create_by` BIGINT(50) NULL DEFAULT NULL COMMENT '创建人',
	`update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
	`update_by` BIGINT(50) NULL DEFAULT NULL COMMENT '更新人',
	PRIMARY KEY (`id`)
)
COMMENT='用户的静脉表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=18
;


